language: java
jdk:
  - oraclejdk8
sudo: required
cache:
  directories:
    - $HOME/.m2
install: true
before_script: travis_wait 45 ./mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script: ./mvn test